default: &default
  store_options:
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  # Use the primary database instead of separate cache database
  database: primary
  <<: *default
