default: &default
  adapter: postgresql
  encoding: unicode
  username: toko

development:
  <<: *default
  database: instaclone_development

test:
  <<: *default
  database: instaclone_test

production:
  primary:
    url: <%= ENV['DATABASE_URL'] %>
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    timeout: 5000
