default: &default
  adapter: postgresql
  encoding: unicode
  username: toko

development:
  <<: *default
  database: instaclone_development

test:
  <<: *default
  database: instaclone_test

production:
  primary:
    <<: *default
    database: instaclone_production
  cache:
    <<: *default
    database: instaclone_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: instaclone_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: instaclone_production_cable
    migrations_paths: db/cable_migrate
