default: &default
  adapter: postgresql
  encoding: unicode
  username: toko

development:
  <<: *default
  database: instaclone_development

test:
  <<: *default
  database: instaclone_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  connect_timeout: 5
