service: instaclone

image: toatoko/instaclone

servers:
  web:
    - 13.62.49.119

proxy:
  ssl: true
  host: blog-test.website
  app_port: 80
  healthcheck:
    path: /up
    interval: 10
    timeout: 30

registry:
  username: toatoko
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY
  clear:
    DATABASE_URL: postgresql://postgres:monster.1@database-2.cnemy8sqwtiz.eu-north-1.rds.amazonaws.com:5432/postgres
  # Remove this if you run Solid Queue as a separate job role
  # SOLID_QUEUE_IN_PUMA: true

volumes:
  - "insta_clone_storage:/rails/storage"

asset_path: /rails/public/assets

builder:
  arch: amd64

ssh:
  user: ubuntu
  keys:
    - /home/toko/Downloads/mamamia.pem

roles:
  web:
    # Starts your Rails server (Puma)
    cmd: bundle exec puma -C config/puma.rb
  job:
    # Starts Solid Queue worker separately from Puma
    cmd: bin/rails solid_queue:start
